
const questions = [
    'What is React?',
'What are the major features of React?',
'What is JSX?',
'What is the difference between Element and Component?',
'How to create components in React?',
'When to use a Class Component over a Function Component?',
'What are Pure Components?',
'What is state in React?',
'What are props in React?',
'What is the difference between state and props?',
'Why should we not update the state directly?',
'What is the purpose of callback function as an argument of setState()?',
'What is the difference between HTML and React event handling?',
'How to bind methods or event handlers in JSX callbacks?',
'How to pass a parameter to an event handler or callback?',
'What are synthetic events in React?',
'What are inline conditional expressions?',
'What is "key" prop and what is the benefit of using it in arrays of elements?',
'What is the use of refs?',
'How to create refs?',
'What are forward refs?',
'Which is preferred option with in callback refs and findDOMNode()?',
'Why are String Refs legacy?',
'What is Virtual DOM?',
'How Virtual DOM works?',
'What is the difference between Shadow DOM and Virtual DOM?',
'What is React Fiber?',
'What is the main goal of React Fiber?',
'What are controlled components?',
'What are uncontrolled components?',
'What is the difference between createElement and cloneElement?',
'What is Lifting State Up in React?',
'What are the different phases of component lifecycle?',
'What are the lifecycle methods of React?',
'What are Higher-Order components?',
'How to create props proxy for HOC component?',
'What is context?',
'What is children prop?',
'How to write comments in React?',
'What is the purpose of using super constructor with props argument?',
'What is reconciliation?',
'How to set state with a dynamic key name?',
'What would be the common mistake of function being called every time the component renders?',
'Is lazy function supports named exports?',
'Why React uses className over class attribute?',
'What are fragments?',
'Why fragments are better than container divs?',
'What are portals in React?',
'What are stateless components?',
'What are stateful components?',
'How to apply validation on props in React?',
'What are the advantages of React?',
'What are the limitations of React?',
'What are error boundaries in React v16',
'How are error boundaries handled in React v15?',
'What are the recommended ways for static type checking?',
'What is the use of react-dom package?',
'What is the purpose of render method of react-dom?',
'What is ReactDOMServer?',
'How to use InnerHtml in React?',
'How to use styles in React?',
'How events are different in React?',
'What will happen if you use setState in constructor?',
'What is the impact of indexes as keys?',
'Is it good to use setState() in componentWillMount() method?',
'What will happen if you use props in initial state?',
'How do you conditionally render components?',
'Why we need to be careful when spreading props on DOM elements??',
'How you use decorators in React?',
'How do you memoize a component?',
'How you implement Server-Side Rendering or SSR?',
'How to enable production mode in React?',
'What is CRA and its benefits?',
'What is the lifecycle methods order in mounting?',
'What are the lifecycle methods going to be deprecated in React v16?',
'What is the purpose of getDerivedStateFromProps() lifecycle method?',
'What is the purpose of getSnapshotBeforeUpdate() lifecycle method?',
'Do Hooks replace render props and higher order components?',
'What is the recommended way for naming components?',
'What is the recommended ordering of methods in component class?',
'What is a switching component?',
'Why we need to pass a function to setState()?',
'What is strict mode in React?',
'What are React Mixins?',
'Why is isMounted() an anti-pattern and what is the proper solution?',
'What are the Pointer Events supported in React?',
'Why should component names start with capital letter?',
'Are custom DOM attributes supported in React v16?',
'What is the difference between constructor and getInitialState?',
'Can you force a component to re-render without calling setState?',
'What is the difference between super() and super(props) in React using ES6 classes?',
'How to loop inside JSX?',
'How do you access props in attribute quotes?',
'What is React PropType array with shape?',
'How to conditionally apply class attributes?',
'What is the difference between React and ReactDOM?',
'Why ReactDOM is separated from React?',
'How to use React label element?',
'How to combine multiple inline style objects?',
'How to re-render the view when the browser is resized?',
'What is the difference between setState and replaceState methods?',
'How to listen to state changes?',
'What is the recommended approach of removing an array element in react state?',
'Is it possible to use React without rendering HTML?',
'How to pretty print JSON with React?',
"Why you can't update props in React?",
'How to focus an input element on page load?',
'What are the possible ways of updating objects in state?',
'How can we find the version of React at runtime in the browser?',
'What are the approaches to include polyfills in your create-react-app?',
'How to use https instead of http in create-react-app?',
'How to avoid using relative path imports in create-react-app?',
'How to add Google Analytics for react-router?',
'How to update a component every second?',
'How do you apply vendor prefixes to inline styles in React?',
'How to import and export components using react and ES6?',
'What are the exceptions on React component naming?',
'Why is a component constructor called only once?',
'How to define constants in React?',
'How to programmatically trigger click event in React?',
'Is it possible to use async/await in plain React?',
'What are the common folder structures for React?',
'What are the popular packages for animation?',
'What is the benefit of styles modules?',
'What are the popular React-specific linters?',
'How to make AJAX call and In which component lifecycle methods should I make an AJAX call?',
'What are render props?',

]